### ISSUE TITLE
can not train wordchar2vector.py

### ISSUE THREAD

**Issue by gosha20777** [Koziev/chatbot#1]
Здравствуйте!
я хотел поробывать вашего бота. и ппри попытке собрать его при запуски тренировки я получил ошибку:
```
There are 396001 known words
max_word_len=29
train set contains 276865 words
val set contains 119136 words
Traceback (most recent call last):
  File "wordchar2vector.py", line 103, in <module>
    trainer.train(input_path, tmp_dir, nb_samples)
  File "A:\Temp\chatbot-master\PyModels\trainers\wordchar2vector_trainer.py", line 249, in train
    index2char = dict([(i, c) for c, i in char2index.iteritems()])
AttributeError: 'dict' object has no attribute 'iteritems'
```

я запускал скрипт с параметрами:
`python wordchar2vector.py --train 1 --i ../tmp/known_words.txt --o ../tmp/wordchar2vector.dat --model_dir ../tmp --arch_type rnn --tunable_char_embeddings 0 --char_dims 0 --batch_size 250 --dims 56`

**Comment by Koziev** [comment]
Добрый день, Георгий,

> я хотел поробывать вашего бота. и ппри попытке собрать его при запуски тренировки я получил ошибку:


запускаете под третьим питоном, да?

**Comment by gosha20777** [comment]
да, собрал
 изменил `char2index.iteritems()` на `char2index.items()`

запускаю под Windows) Для этого пришлось 5 библиотек перекомпилировать вручную с помошью CMake и VS Studio)))

Пол дня мучений - и все. обучение началось....

У меня могут возникнуть еще некоторые вопросы по этому поводу. Можете дать свои контакты?

**Comment by Koziev** [comment]
Спасибо за информацию об ошибке, заменил в исходниках dict.iteritems() на six.iteritems(), чтобы работало в третьем питоне.

Для контактов можно оставлять вопросы и здесь или на inkoziev@gmail.com, в принципе будет одинаково по скорости.
