### ISSUE TITLE
Недостающиейся файлы

### ISSUE THREAD

**Issue by timeshift92** [Koziev/chatbot#10]
Доброго времени суток, подскажите пожалуйста где можно найти следующие файлы:
 ---> corpora/Corpus/ (все файлы из этой директории) 
---> nonrelevant_premise_questions.txt (хотябы пример я пока создал пустышку но что там должно быть пока не понимаю)
---> contradictions.txt
---> qa_multy
---> united_corpora.dat
---> morpheval_corpus_solarix.full.dat

**Comment by timeshift92** [comment]
мне очень нравится ваш проект, но пока понять все этого трудно такому новичку как я :( хотел узнать возможно ли записать все данные которые используется уже на работающим боте в один yml
я даже готов помочь если вы подскажете какие файли используется непосредственно у работающего бота
также я бы отдельно соберу дата сеты для обучение, тогда бы у вас получится уже что-то типа фреймворка

**Comment by Koziev** [comment]
Привет,

> ---> nonrelevant_premise_questions.txt (хотябы пример я пока создал пустышку но что там должно быть пока не понимаю)
> ---> contradictions.txt
> ---> qa_multy
Добавил в реп примеры этих трех файлов.

---> united_corpora.dat
---> morpheval_corpus_solarix.full.dat
Эти файлы проще заменить пустыми текстовиками. Из них при формировании датасетов берется только лексика, чтобы отсеять неупотребляющиеся слова и не тащить их в релиз. 

---> corpora/Corpus/ (все файлы из этой директории)
Тут просто лежит огромный текстовый корпус - больше сотни Гб русскочзычных текстов. В принципе, тоже можно пустым файлом заменить.

> я даже готов помочь если вы подскажете какие файли используется непосредственно у работающего бота
> также я бы отдельно соберу дата сеты для обучение, тогда бы у вас получится уже что-то типа фреймворка

Спасибо, любая помощь будет очень кстати. Но я пока воздерживаюсь от того, чтобы прямо делать целый фреймворк-конструктор для чатботов. Сейчас качество отдельных частей иногда меня не устраивает, поэтому время от времени архитектуру и используемые датасеты приходится кардинально менять. В этих условиях даже нормальную документацию по подготовке датасетов невозможно сделать, она быстро устареет. Сейчас вот экспериментирую с генеративной грамматикой для обеспечения более "человечного" ответа бота, тоже могут быть в результате сильные изменения внутри. Из более-менее стабильных вещей, которые легко можно модифицировать сейчас есть только база фактов (файлы premises*.txt) и реплики (smalltalk.txt), оттуда чатбот и берет информацию для ответов.
