### ISSUE TITLE
Отсутствует папка chatbot/PyModels/utils

### ISSUE THREAD

**Issue by geonft** [Koziev/chatbot#11]
Добрый день,
Похоже, в проекте отсутствует папка chatbot/PyModels/utils

**Comment by Koziev** [comment]
Добрый день,

> Похоже, в проекте отсутствует папка chatbot/PyModels/utils
угу, спасибо за замечание, закомитил: https://github.com/Koziev/chatbot/tree/master/PyModels/utils
