### ISSUE TITLE
Ошибка No module named 'bot.simple_facts_storage'

### ISSUE THREAD

**Issue by GraphGrailAi** [Koziev/chatbot#17]
joo@joo-tf:~/Документы/LocalRepository/chatbot-0.0.0.13-alpha/scripts$ sh console_bot.sh
Traceback (most recent call last):
  File "../PyModels/console_chatbot.py", line 11, in <module>
    from bot.profile_facts_reader import ProfileFactsReader
  File "/home/joo/Документы/LocalRepository/chatbot-0.0.0.13-alpha/PyModels/bot/profile_facts_reader.py", line 7, in <module>
    from bot.simple_facts_storage import SimpleFactsStorage
ModuleNotFoundError: No module named 'bot.simple_facts_storage'

Файла нет.
Оффтоп: в прошлых версиях у меня были проблемы с импортом многих модулей, пришлось вручную проставить точки from . , чтобы импорты сработали, не писал ишью об этом, думал что-то у меня не так с импортами, хотя питон должен это понимать

**Comment by Koziev** [comment]
Привет,

> ModuleNotFoundError: No module named 'bot.simple_facts_storage'
> Файла нет.

Ага, спасибо, потерялся в ходе чистки. Добавил его.

> думал что-то у меня не так с импортами, хотя питон должен это понимать

А какая версия питона? Я пока все проверяю только на 2й ветке, на 3 еще не перевел проект, могут быть несовметимости.

**Comment by GraphGrailAi** [comment]
> А какая версия питона?

Анаконда, 3.6.8 питон, это же стандарт сейчас

**Comment by Koziev** [comment]
> Анаконда, 3.6.8 питон, это же стандарт сейчас

Да, действительно, под третью ветку пришлось сделать некоторые правки в исходниках.
Сейчас вроде все поправил, в докере бот стартует уже в 3-м питоне.

**Comment by GraphGrailAi** [comment]
Круто, хорошо. 
Я вот думаю, а может у меня фласк не работал из-за питона. А вот консоль работала выходит сразу в обеих версиях, что интересно,

**Comment by GraphGrailAi** [comment]
Круто, хорошо. 
Я вот думаю, а может у меня фласк не работал из-за питона. А вот консоль работала выходит сразу в обеих версиях, что интересно,

**Comment by Koziev** [comment]
> А вот консоль работала выходит сразу в обеих версиях, что интересно,
На самом деле до этого бот не работал в 3й питоне как раз из-за нескльких кривых импортов. Во 2м питоне они прокатывали. Я все правки закомитил вчера и контейнер пересобрал.
