### ISSUE TITLE
Команды

### ISSUE THREAD

**Issue by fancat-programer** [Koziev/chatbot#25]
Приветствую. Мне очень нравится ваш проект. Могли бы вы сделать команды, то есть человек написал "открой xxxxx", и выполнился код?

**Comment by Koziev** [comment]
Привет,

>Могли бы вы сделать команды, то есть человек написал "открой xxxxx", и выполнился код?

Я там уже делал что-то подобное.

В [строке 24 в console_chatbot.py](https://github.com/Koziev/chatbot/blob/master/ruchatbot/frontend/console_chatbot.py#L24) есть дефолтный обработчик любых приказов, если они не были обработаны явным правилом.

Там же есть обработчик on_check_emails, должен срабатывать на приказы типа "проверь почту". Эти обработчики регистрируются в [строке 133](https://github.com/Koziev/chatbot/blob/master/ruchatbot/frontend/console_chatbot.py#L133) и далее. Правило, которое срабатывает на ключевые фразы - [вот эта строка в файле rules.yaml](https://github.com/Koziev/chatbot/blob/master/data/rules.yaml#L3245).

**Comment by fancat-programer** [comment]
Спасибо. Буду экспериментировать.
