### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by koval01** [Koziev/chatbot#28]
Как запустить телеграм бота? Или эта опция сейчас недоступна?

**Comment by Koziev** [comment]
Привет,
>Как запустить телеграм бота? Или эта опция сейчас недоступна?

tg-бот был (https://github.com/Koziev/chatbot/blob/master/ruchatbot/frontend/telegram_bot.py), потом я его перестал поддерживать. Сейчас этот код в репозитории не рабочий. В ближайшем релизе я его собираюсь актуализировать.

**Comment by koval01** [comment]
Спасибо за информацию.

**Comment by koval01** [comment]
Вы восстановили Телеграмм версию бота, спасибо. Но я не понимаю как его запустить, после запуска я получаю ошибку "Модуль Telegram отсутствует". Я запускал напрямую через python, поскольку Shell скрипт запуска не нашел. Команда для запуска которую я использовал - docker run -it chatbot python3 /chatbot/ruchatbot/scripts/telegram_bot.sh

**Comment by Koziev** [comment]
Привет,

>Но я не понимаю как его запустить

к сожалению, я не спел сделать удобный запуск tg-бота из докер-образа (если это вообще удасться сделать).

На данный момент для запуска нужно:  

1) зарегать свой бот в телеграмме, получить токен.  
2) извлечь из образа весь дистр бота  
3) установить пакет python-telegram-bot  
4) запускать бота примерно так:  

```
python3 ruchatbot/frontend/telegram_bot.py --token XXX --profile ../../data/profile_1.json --models_folder ../../tmp --w2v_folder ../../tmp --tmp_folder ../../tmp --data_folder ../../data
```
Надеюсь, в следующем релизе получиться запускать tg-бота без всех этих танцев, прямо из докера.
