### ISSUE TITLE
Не запоминает мое имя

### ISSUE THREAD

**Issue by koval01** [Koziev/chatbot#29]
H:> Как меня зовут?

B:> не могу ответить, так как нет данных
H:> Меня зовут Ярослав

B:> Добрый день, Вячеслав
H:> ДУРА, я Ярослав

B:> Ой, мне такие слова не нравятся
H:> Как меня зовут?

B:> яшав
H:> Чего?

B:> Чтобы творить добро

**Comment by Koziev** [comment]
Привет,
> H:> Меня зовут Ярослав
> B:> Добрый день, Вячеслав

мда, эпично, спасибо за ошибку :)
Надо заметить, что модель подставила одно из знакомых ей имен, а не просто левое слово. Просто в обучающем датасете имя "Ярослав" вообще не встречается, вот и результат. Надо будет добавить.

**Comment by GraphGrailAi** [comment]
Просто в обучающем датасете имя "Ярослав" вообще не встречается, вот и результат. Надо будет добавить.

- тут проблема глобальнее: даже если добавить это имя, другое имя которого нет модель все равн оне будет знать. Также и с иностранными именами. Надо что-то типа BERT модель применять чтобы полностью решить вопрос

**Comment by Koziev** [comment]
>Надо что-то типа BERT модель применять чтобы полностью решить вопрос

Да, согласен. Несколько моделей в пайплане бота уже есть в альтернативном варианте поверх эмбеддингов BERT. Но чтобы перейти, надо еще и дистилляцией позаниматься, много возни.

**Comment by mikhail0920** [comment]
> > Надо что-то типа BERT модель применять чтобы полностью решить вопрос
> 
> Да, согласен. Несколько моделей в пайплане бота уже есть в альтернативном варианте поверх эмбеддингов BERT. Но чтобы перейти, надо еще и дистилляцией позаниматься, много возни.

Могу предложить использовать pymorphy2. Я в боте через него сделал выделение именных тегов)
