### ISSUE TITLE
pypy

### ISSUE THREAD

**Issue by koval01** [Koziev/chatbot#35]
Планируете ли перейти на [pypy](https://www.pypy.org/)?

**Comment by Koziev** [comment]
>Планируете ли перейти на pypy?

боюсь, я не понял вопрос :(

**Comment by koval01** [comment]
pypy это более быстрый интерпретатор Python кода

**Comment by Koziev** [comment]
>pypy это более быстрый интерпретатор Python кода

Спасибо за пояснение, теперь понял.

К сожалению, в этом боте практически все узкие места образуются из-за ML'ных моделей. Я даже оставил в проде некоторые модели из-за их скорости, хотя есть более качественные варианты на нейросетках. Нейросетки любят GPU'шки.

В общем, ускорение самой интерпретации питоновского кода не даст особого эффекта, так как основной затык - в скомпилированном C++ коде библиотек типа tensorflow.

**Comment by koval01** [comment]
Спасибо за ответ.
