### ISSUE TITLE
Ошибка при работе с телеграм ботом

### ISSUE THREAD

**Issue by RFContracts** [Koziev/chatbot#37]
telegram.ext.dispatcher  - Processing Update: {'update_id': 123, 'message': {'message_id': 618, 'date': 1612791283, 'chat': {'id': 286010947, 'type': 'private', 'username': 'username', 'first_name': 'name'}, 'text': 'привет', 'entities': [], 'caption_entities': [], 'photo': [], 'new_chat_members': [], 'new_chat_photo': [], 'delete_chat_photo': False, 'group_chat_created': False, 'supergroup_chat_created': False, 'channel_chat_created': False, 'from': {'id': 286010947, 'first_name': 'Sergey', 'is_bot': False, 'username': 'DevMentor', 'language_code': 'ru'}}}
2021-02-08 13:34:39 ERROR    root  - 'CallbackContext' object has no attribute 'message'

В файле telegram_bot.py вы используете библиотеку telegram.ext на 20 и 32 строчке в фукнцию прокидывается 2 переменные, но в новой версии библиотеки там немного по другому.

Пример из документации:
def echo(update, context):
    context.bot.send_message(chat_id=update.effective_chat.id, text=update.message.text)

from telegram.ext import MessageHandler, Filters
echo_handler = MessageHandler(Filters.text & (~Filters.command), echo)
dispatcher.add_handler(echo_handler)

У вас примерно так:
def echo(bot, update):
...
bot.send_message(chat_id=update.message.chat_id, text=answer)

поэтому в вашем варианте он в объекте update не видит атрибута message.

**Comment by RFContracts** [comment]
Еще если у юзера нет update.message.chat.last_name, то будет выдавать ошибку, лучше str(update.message.chat_id)

**Comment by RFContracts** [comment]
Пофиксил, заюзал у себя в контейнере, отправил вам пул риквест https://github.com/Koziev/chatbot/pull/38 буду признателен если пофиксите.

**Comment by Koziev** [comment]
Спасибо большое, действительно на актуальной версии библиотеки бота надо пофиксить.
Забрал pr.
Поправил опечатку в имени переменной в строке 48.
После всех изменений бот нормально заработал в телеграмме.
