### ISSUE TITLE
Сборка #2

### ISSUE THREAD

**Issue by BANanaD3V** [Koziev/chatbot#48]
Это опять я XD

Собираю, все сделал, вылазит ошибка 
```
for r in self.cur.execute('SELECT id_tagsets FROM word_tagsets WHERE word=:word', {'word': word}):
sqlite3.OperationalError: no such table: word_tagsets
```

Есть версия .db файла поновее? Намного поновее?

**Comment by BANanaD3V** [comment]
Заменил на самую новую, все еще преследует ошибка. Help pls.

**Comment by BANanaD3V** [comment]
А ещё я пробовал качать репо, разархивить, идти в репо и туда добавить .db

Через dockerfile. Сработало, но даёт эту же ошибку...

**Comment by Koziev** [comment]
Привет,

по идее вот этот файл, который у меня локально в пакете ruword2tags используется: https://disk.yandex.ru/d/JTG72ITGxb-E6Q

Его надо скопировать туда, где установлен ruword2tags.

Есть крошечная вероятность, что новые версии SQLite несовместимы по формату файла БД со старыми, я честно говоря не отслеживал их changelog. Но поскольку модуль sqlite входит в стандартные пакеты питона, я сомневаюсь, что причина в этом.

**Comment by BANanaD3V** [comment]
> Есть крошечная вероятность, что новые версии SQLite несовместимы по формату файла БД со старыми, я честно говоря не отслеживал их changelog. Но поскольку модуль sqlite входит в стандартные пакеты питона, я сомневаюсь, что причина в этом.

Питон 3.6.2, тоже сомневаюсь (очень) что проблема в sqlite. let me try new file.

**Comment by BANanaD3V** [comment]
Не хочет. Я немного изменил докерфайл так как из .tar.gz не хочет работать. 
```
RUN pip install git+https://github.com/BANanaD3V/ruword2tags
WORKDIR /usr/local/lib/python3.6/site-packages/
ADD ruword2tags.db /ruword2tags
```

Что можно сделать чтобы заменить. А еще можно без сборки в докер запускать?

**Comment by BANanaD3V** [comment]
Вот мой фулл докерфайл, если нужно.

```
FROM python:3.6-slim

SHELL ["/bin/bash", "-c"]

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

RUN apt-get update
RUN apt-get install -y python python3-pip
RUN apt-get -y install git-core
RUN apt-get install -y liblzma-dev

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install git+https://github.com/Koziev/rulemma
RUN pip uninstall -y numpy
RUN yes | apt-get install python3-numpy

RUN pip install torch==1.7.1
RUN pip install tensorflow==2.4.0
RUN pip install transformers==4.1.1
RUN pip install keras==2.4.3
RUN pip install sentencepiece
RUN pip install lightgbm
RUN pip install scikit-learn==0.24.0
RUN pip install python-Levenshtein
RUN pip install gensim
RUN pip install pathlib
RUN pip install python-crfsuite
RUN pip install colorama
RUN pip install coloredlogs
RUN pip install git+https://www.github.com/keras-team/keras-contrib.git
RUN pip install requests
RUN pip install flask
RUN pip install flask_sqlalchemy
RUN pip install flask_wtf
RUN pip install python-telegram-bot --upgrade
RUN pip install h5py==2.10.0
RUN pip install pyconll
RUN pip install ufal.udpipe

RUN pip install git+https://github.com/BANanaD3V/ruword2tags
WORKDIR /usr/local/lib/python3.6/site-packages/ruword2tags
ADD ruword2tags.db /ruword2tags

RUN pip install git+https://github.com/Koziev/rutokenizer
RUN pip install git+https://github.com/Koziev/rupostagger
RUN pip install git+https://github.com/Koziev/rusyllab
RUN pip install git+https://github.com/Koziev/ruchunker

RUN apt-get clean

WORKDIR /chatbot/ruchatbot/bot
COPY ./ruchatbot/bot/*.py ./

WORKDIR /chatbot/ruchatbot/frontend
COPY ./ruchatbot/frontend/*.py ./

WORKDIR /chatbot/ruchatbot/bot_service
COPY ./ruchatbot/bot_service/*.py ./

WORKDIR /chatbot/ruchatbot/bot_service/static/img
COPY ./ruchatbot/bot_service/static/img/*.* ./

WORKDIR /chatbot/ruchatbot/bot_service/templates
COPY ./ruchatbot/bot_service/templates/*.* ./


WORKDIR /chatbot/ruchatbot/utils
COPY ./ruchatbot/utils/*.py ./

WORKDIR /chatbot/ruchatbot/layers
COPY ./ruchatbot/layers/*.py ./

WORKDIR /chatbot/ruchatbot/scenarios
COPY ./ruchatbot/scenarios/*.py ./

WORKDIR /chatbot/ruchatbot/generative_grammar
COPY ./ruchatbot/generative_grammar/*.py ./

WORKDIR /chatbot/ruchatbot
COPY ./ruchatbot/__init__.py ./
COPY ./ruchatbot/qa_machine.py ./

WORKDIR /chatbot/data
COPY ./data/*.* ./

WORKDIR /chatbot/tmp/rugpt_chitchat
COPY ./tmp/rugpt_chitchat/*.* ./

WORKDIR /chatbot/tmp/rugpt_premise4question
COPY ./tmp/rugpt_premise4question/*.* ./

WORKDIR /chatbot/tmp
COPY ./tmp/*.* ./

WORKDIR /chatbot/scripts
COPY ./scripts/console_bot.sh ./
COPY ./scripts/flask_bot.sh ./
COPY ./scripts/tg_bot.sh ./

WORKDIR /chatbot
COPY CHANGELOG.txt ./

EXPOSE 9001
WORKDIR /chatbot/scripts
CMD "./console_bot.sh"
```

**Comment by BANanaD3V** [comment]
Я как думаю нужно через docker cp еще заменить попробовать.

**Comment by BANanaD3V** [comment]
Не выходит...

**Comment by BANanaD3V** [comment]
Есть идеи? Я уже перепробовал все, Даже скачал все без докера, запускается но дает ошибку что нет ruchatbot.layers...

**Comment by BANanaD3V** [comment]
:( Запустил, модель корявая. Я пожалуй удалю всю модель и тупо копирую tmp из докер образа целиком, так будет лучше. Trying.

**Comment by BANanaD3V** [comment]
Не работает. Что делать?

**Comment by Koziev** [comment]
А попробуйте, пожалуйста, в консоли открыть файл базы данных ```ruword2tags.db```, например с помощью пакета sqlite3. У меня это выглядит так:

```
inkoziev@devbox1080:~/github/ruword2tags/ruword2tags$ sqlite3 ruword2tags.db 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> SELECT id_tagsets FROM word_tagsets WHERE word='кошка';
118
```

**Comment by BANanaD3V** [comment]
> А попробуйте, пожалуйста, в консоли открыть файл базы данных `ruword2tags.db`, например с помощью пакета sqlite3. У меня это выглядит так:
> 
> ```
> inkoziev@devbox1080:~/github/ruword2tags/ruword2tags$ sqlite3 ruword2tags.db 
> SQLite version 3.31.1 2020-01-27 19:55:54
> Enter ".help" for usage hints.
> sqlite> SELECT id_tagsets FROM word_tagsets WHERE word='кошка';
> 118
> ```

Сейчас попробую.

**Comment by BANanaD3V** [comment]
sqlite> SELECT id_tagsets FROM word_tagsets WHERE word='кошка';
118

да вот тоже работает...

**Comment by BANanaD3V** [comment]
Что делать?

**Comment by Koziev** [comment]
Если файл БД нормально открывается и отрабатывает выборка, значит причина в чем-то другом. Попробуйте в питоновской консоли сделать примерно так:

```
>>> import ruword2tags
>>> d = ruword2tags.RuWord2Tags()
>>> d.load()
>>> list(d['кошка'])

['СУЩЕСТВИТЕЛЬНОЕ ОДУШ=ОДУШ ПАДЕЖ=ИМ РОД=ЖЕН ЧИСЛО=ЕД']
```

Если будет опять ошибка работы с БД, то проверьте запрос к БД в папке, где установлен пакет - ее можно увидеть с помощью "pip show ruword2tags".

**Comment by BANanaD3V** [comment]
> Если файл БД нормально открывается и отрабатывает выборка, значит причина в чем-то другом. Попробуйте в питоновской консоли сделать примерно так:
> 
> ```
> >>> import ruword2tags
> >>> d = ruword2tags.RuWord2Tags()
> >>> d.load()
> >>> list(d['кошка'])
> 
> ['СУЩЕСТВИТЕЛЬНОЕ ОДУШ=ОДУШ ПАДЕЖ=ИМ РОД=ЖЕН ЧИСЛО=ЕД']
> ```
> 
> Если будет опять ошибка работы с БД, то проверьте запрос к БД в папке, где установлен пакет - ее можно увидеть с помощью "pip show ruword2tags".
> 
> 

Скорее всего я не так гружу репо, я сверху кидал как пробовал докер файл менять. Не работает.

**Comment by Koziev** [comment]
Тогда остается только пошаговая отладка - попробуйте войти внутрь вызова d.load(), увидеть фактический путь к открываемой БД вот в этой строке https://github.com/Koziev/ruword2tags/blob/master/ruword2tags/ruword2tags.py#L96

**Comment by BANanaD3V** [comment]
Может быть в моем докер файле плохо грузит пакет и файл, я его менял все таки. Есть советы?

**Comment by Koziev** [comment]
>Может быть в моем докер файле плохо грузит пакет и файл, я его менял все таки. Есть советы?

Я ставлю его так.

1) В папке сборки образа сделан архив с пакетом:
https://drive.google.com/file/d/1BEzkHcaV7REROrC11YC1_JWNFq6qPUjU/view?usp=sharing

2) При сборке образа этот архив копируется внутрь образа, распаковывается и устанавливается:

```
WORKDIR /home
ADD ruword2tags.tar.gz /home
WORKDIR /home/ruword2tags
RUN pip install .
```

**Comment by Anastazziya** [comment]
> Может быть в моем докере файл плохо грузит пакет и файл, я его поменял все таки. Есть советы?

Здравствуйте. У Вас получилось собрать проект?

**Comment by BANanaD3V** [comment]
> > Может быть в моем докере файл плохо грузит пакет и файл, я его поменял все таки. Есть советы?
> 
> Здравствуйте. У Вас получилось собрать проект? 
> 

Нет.
