### ISSUE TITLE
web-служба для общения по API c сервисом бота

### ISSUE THREAD

**Issue by vpinigin** [Koziev/chatbot#52]
привет! 

подскажи пожалуйста
1) есть ли возможно запустить бота в режим веб-сервиса, чтобы можно было извне присылать запросы с текстом сообщения и получить в ответ в какой-то форме (json) ответы бота? 
2) если есть, то как это запускать из текущей версии master?  какие там есть параметры?
3) можно хотябы один пример запроса написать, чтобы от него я уже понимал логику и строил свои (самый простой тип "привет")

**Comment by Koziev** [comment]
Привет,

Вот тут лежит скрипт, который запускает rest api: https://github.com/Koziev/chatbot/blob/master/scripts/flask_bot.sh

Код веб-сервиса находится тут: https://github.com/Koziev/chatbot/blob/master/ruchatbot/bot_service/routes.py

API там очень примитивный:

Старт сессии для пользователя user_id:
```
http://127.0.0.1:9000/start_conversation?user=user_id
```

Обработка реплики собеседника:
```
http://127.0.0.1:9000/push_phrase?user=user_id?phrase=привет
```

Извлечение очередной сгенерированной реплики бота (может быть несколько, надо извлекать, пока не вернется пустота):

```
http://127.0.0.1:9000/pop_phrase?user=user_id
```

**Comment by vpinigin** [comment]
класс, спасибо

**Comment by Pererozhdennyy** [comment]
``

> класс, спасибо

на каких системных требованиях ты запускаешь?

**Comment by vpinigin** [comment]
> ``
> 
> > класс, спасибо
> 
> на каких системных требованиях ты запускаешь?

да я для теста пока запускаю в виртуалке 
8гб рам, серверный проц Intel Xeon W-2255 3.7 ГГц

в целом достаточно медленно работает, но как я понимаю, в идеале надо надо на машие с GPU запускать

**Comment by Pererozhdennyy** [comment]
> > ``
> > > класс, спасибо
> > 
> > 
> > на каких системных требованиях ты запускаешь?
> 
> да я для теста пока запускаю в виртуалке 8гб рам, серверный проц Intel Xeon W-2255 3.7 ГГц
> 
> в целом достаточно медленно работает, но как я понимаю, в идеале надо надо на машие с GPU запускать

а вот тут я не понимаю, как у Вас получилось, раз у меня бьёт ошибку недосточно ОЗУ (у меня 16), требует минимум 31 гб...

**Comment by Den4ikAI** [comment]
> > > ``
> > > > класс, спасибо
> > > 
> > > 
> > > на каких системных требованиях ты запускаешь?
> > 
> > 
> > да я для теста пока запускаю в виртуалке 8гб рам, серверный проц Intel Xeon W-2255 3.7 ГГц
> > в целом достаточно медленно работает, но как я понимаю, в идеале надо надо на машие с GPU запускать
> 
> а вот тут я не понимаю, как у Вас получилось, раз у меня бьёт ошибку недосточно ОЗУ (у меня 16), требует минимум 31 гб...

Скорее всего нужно отключить debugging при запуске.
