### ISSUE TITLE
Closure detector

### ISSUE THREAD

**Issue by Den4ikAI** [Koziev/chatbot#56]
Модель ведет себя странно
Накидал код инференса и получаю подобное:

> Как тебя зовут?
0.9988352656364441
> Что делаешь?
0.9995481371879578
> Сколько будет 5+5?
0.999200165271759
> Когда родился А.С Пушкин?
0.9989402890205383

Похоже, модель просто не работает :(
Если есть возможность, отправьте датасет для обучения.
Заранее спасибо

**Comment by Koziev** [comment]
Привет!

Проверь, пожалуйста, версию торча. Модель работает с torch>=1.8, а с 1.6 например инференс как раз поломан с такими симптомами (почти всегда выдает ~1). Между этими версиями торча были изменения, которые поломали обратную совместимость на некоторых моделях.

**Comment by Den4ikAI** [comment]
У меня была похожая проблема связанная с версиями transformers. Я запускаю вроде на 4.22. Глянул, какую вы используете в докере и думаю поставить ее. 
Моя версия torch - 1.12 с cuda 11.3

**Comment by Koziev** [comment]
Да, должно помочь, вот тут актуальный список версий: https://github.com/Koziev/chatbot/blob/core_v4/dockerfile#L17

Хотя от версии трансформерс врожде работа этой модельки не зависит, только от торча.
Занятно, что например гптэхи никак не реагируют на версию торча, работают нормально.
Не удивлюсь, если тут и мои "прямые" руки замешаны.

**Comment by Den4ikAI** [comment]
А вот гэпетэхи как раз реагируют на Трансформеры. Например tinkoff-ai/ruDialoGPT-medium сходит с ума при версии transformers>1.12 вроде. Но только если есть подача контекста

**Comment by Den4ikAI** [comment]
Да, я поменял версии библиотек и все работает.
