### ISSUE TITLE
Запуск через Docker

### ISSUE THREAD

**Issue by timeshift92** [Koziev/chatbot#6]
Здравствуйте, при запуске через докер выдает такую ошибку, можете подсказать в чем проблема?

python_1  | Using TensorFlow backend.
python_1  | 2019-04-02 14:29:12,889 Loading lexicon from ../data/ru_word2lemma.tsv.gz
python_1  | 2019-04-02 14:29:14,176 Lexicon loaded: 88527 lemmas, 288259 wordforms
python_1  | Killed
chatbotdocker_python_1 exited with code 137

**Comment by Koziev** [comment]
Добрый день,

> python_1 | Killed

сам с таким не сталкивался, но подозреваю, что памяти не хватило.

**Comment by timeshift92** [comment]
Спасибо, тоже не обратил сразу внимание, закрываю
