### ISSUE TITLE
SolarixGrammarEngineNET

### ISSUE THREAD

**Issue by timeshift92** [Koziev/chatbot#9]
Здравствуйте, а  

1. SolarixGrammarEngineNET.GrammarEngine2 
2. SolarixGrammarEngineNET.SyntaxTreeNode

доступна только в платном режиме

**Comment by Koziev** [comment]
Добрый день,


>    1. SolarixGrammarEngineNET.GrammarEngine2
>    2. SolarixGrammarEngineNET.SyntaxTreeNode
>
> Платной версии грамматического словаря нет, осталась только бесплатная.
Весь код лежит в репозитории https://github.com/Koziev/GrammarEngine, в
частности .NET-обертка GrammarEngine2 лежит в файле
https://github.com/Koziev/GrammarEngine/blob/master/src/demo/ai/solarix/engines/gren_fx2/Class1.cs
